accounts/urls.py
from django.conf.urls import url 
from . import views

app_name = 'accounts'

urlpatterns = [

	# url(r'^signup/$', views.signup_view, name= "signup"),
	url(r'^login/$', views.login_view, name= "login"),
	url(r'^logout/$', views.logout_view, name= "logout"),

]

blog/urls.py
from django.conf.urls import url 
from . import views


app_name = 'blog'

urlpatterns = [
	url(r'^$',views.post_list, name='list'),
	url(r'^posts/$',views.post_archive, name='posts'),
	url(r'^post/(?P<slug>[\w-]+)/$',views.Detail.post_details, name='detail'),
	
	
	

	
]

myblog/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path

# To Add Static and Media Files path 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

# To add views url
from . import views



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.home),
	url(r'^home/$',views.home, name= 'home'),
    url(r'signup/$',views.signup, name = 'signup'),
    url(r'^blog/',include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('secret/', views.secret_page, name= 'secret'),
    url(r'^upload/$', views.upload, name='upload'),
    # path('secret2/', views.SecretPage.as_view(), name= 'secret2')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=100)
	text = models.TextField()
	published_date = models.DateTimeField(auto_now_add=True)
	thumnail = models.ImageField(default='default.png', blank=True)

	def __str__(self):
		return self.title

	def snippet(self):
		return self.text[:256]+'...'

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
	user = models.ForeignKey(User, max_length=250, on_delete=models.CASCADE)
	comment = models.CharField(max_length=500, default=None)	
	time = models.DateTimeField(auto_now_add=True)
	# approved = models.BooleanField(default=False)

	# def approved(self):
	# 	self.approved = True
	# 	self.save()
	# def __str__(self):
	# 	return self.body 

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	# post = forms.CharField()
	
	class Meta(object):
		"""docstring for Meta"""
		model = Comment
		fields = ('comment',)
		
			

myblog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
	"""docstring for ClassName"""
	first_name = forms.CharField(max_length=40, required =False, help_text='optional.')
	last_name = forms.CharField(max_length=40, required =False, help_text='optional.')
	email = forms.EmailField(max_length=254, help_text='required, Please enter valid email address.')

	class Meta(object):
		"""docstring for Meta"""
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
			

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# from django.urls import reverse
# from django.http import HttpResponse

# Create your views here.

# def signup_view(request):

# 	if request.method == 'POST':
# 		form = UserCreationForm(request.POST)
# 		if form.is_valid():
# 			user=form.save()
# 			login(request, user)
# 			return redirect('blog:list')
# 	else:
# 		form = UserCreationForm()
# 	return render(request,'accounts/signup.html',{'form':form})

def login_view(request):

	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request,user)
			return redirect('blog:list')

	else:
		form = AuthenticationForm()
	return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('blog:list')

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .models import Post,Comment
from django.http import HttpResponse
from .forms import CommentForm

# Create your views here.
def post_list(request):

	posts = Post.objects.order_by('published_date')
	return render(request, 'blog/post_list.html',{'posts':posts})


class Detail(TemplateView):

	def post_details(request,slug):
		single_post = Post.objects.get(slug=slug)
		if request.method == 'GET':
			form = CommentForm()
			return render(request, 'blog/blog_detail.html',{'single_post':single_post, 'form': form})

		elif request.method == 'POST':
			form = CommentForm(request.POST)
			if form.is_valid():
				comment = form.save(commit = False)
				comment.post = single_post
				comment.user = request.user
				comment.save()
				form = CommentForm()
				comments = Comment.objects.order_by('time')
				context = {'single_post':single_post,
							'form': form,
							'comments':comments}
			return render(request, 'blog/blog_detail.html',context)

		else:
			form = CommentForm()
		return render(request, 'blog/blog_detail.html',{'single_post':single_post,'form': form})





def post_archive(request):
		form = CommentForm()
		posts = Post.objects.order_by('published_date')
		return render(request, 'blog/archive.html',{'posts':posts})

myblog/views.py
from django.shortcuts import render, redirect
from blog.models import Post
from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,authenticate
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from myblog.forms import SignupForm
from django.core.files.storage import FileSystemStorage

# Create your views here.
def home(request):
	count = User.objects.count()
	posts = Post.objects.order_by('published_date')
	return render(request, 'myblog/home.html',{'posts':posts, 'count':count})

def signup(request):

	if request.method == 'POST':
		form = SignupForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username = username, password = raw_password)
			login(request, user)
			return redirect('home')
	else:
		form = SignupForm()
	return render(request,'myblog/signup.html',{'form':form})

@login_required
def secret_page(request):
	return render(request, 'myblog/secret_page.html')

def upload(request):
	context = {}
	if request.method == 'POST':
		uploaded_file = request.FILES['document']
		fs = FileSystemStorage()
		name = fs.save(uploaded_file.name, uploaded_file, max_length=None)
		context['url'] = fs.url(name)


	return render(request,'myblog/upload.html',context)
































# class SecretPage(LoginRequiredMixin,TemplateView):
# 	template_name = 'myblog/secret_page.html'

accounts/templates/accounts/login.html
{%extends 'myblog/base.html' %}

{% block content %}

	<h2>Login</h2>
	
	<form class="login-form" action="{% url 'accounts:login' %}" method="post">
		
		{% csrf_token %}

		{{form}}

		<input type="submit" value="Login">


	</form>
		


{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'myblog/base.html'%}


{% block content %}

	<h1>Signup</h1>

	<form class="signup-form" action="/accounts/signup/" method="post">

		{%csrf_token%}

		{{form}}
		
		<input type="submit" value="Signup">

	</form>

{% endblock %}

blog/templates/blog/archive.html
{% extends 'myblog/base.html' %}

{%block title%}Archive{%endblock%}
{% load crispy_forms_tags %}

	{% block content %}

		<div>

			<div>

				{% for post in posts %}

					<div>

						<h2 class="post-archive"><a class="post-title " href="{%  url 'blog:detail' slug=post.slug %}" style="text-decoration: none;" >{{post.title}}</a></h2>


					</div>

				{% endfor %}

			</div>


		</div>

	{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'myblog/base.html' %}
{%block title%}Blog{%endblock%}
{% load crispy_forms_tags %}

	{% block content %}

		<div>

			<img class="thumnail-banner" src="{{single_post.thumnail.url}}" alt="thumnail-image" />

			<h2 class="h2-post-title shadow-lg p-3 mb-5 bg-white rounded">{{single_post.title}}</h2>

			<p class= "post-text shadow p-3 mb-5 bg-white rounded">{{single_post.text}}</p>

			<p class="published-date">Published by {{single_post.author}}  @{{single_post.published_date}}</p>

			<p>Total number of comments: {{single_post.comments.count}}</p>

			

				{% if request.user.is_authenticated %}

					{% for comment in single_post.comments.all %}
						<p>{{comment.comment}}<p>
						<p>{{comment.user}}</p>
						<p>{{comment.time}}</p>
					{% empty %}
						<p> There is no Comments</p>
					{% endfor %}
					
					<form method="post">
							
							{% csrf_token %}

							{{form|crispy}}

							<button type="submit" class="btn btn-primary">Post</button>
							

					</form>
				{% endif %}

			  



		</div>

	{% endblock %}

blog/templates/blog/comments.html
{% extends 'myblog/base.html' %}
{%block title%}Blog{%endblock%}
{% load crispy_forms_tags %}

	{% block content %}


			
				<form method="post">
						
						{% csrf_token %}

						{{form|crispy}}

						<button type="submit" class="btn btn-primary">Post</button>
						

				</form>
<!-- 			<p>Total number of comments: {{single_post.comments.count}}</p>
			{% for comment in single_post.comments.all %}
				<p>{{comment.body}}<p>
				<p>{{comment.user}}</p>
				<p>{{comment.time}}</p>
			{% empty %}
				<p> There is no Comments</p>
			{% endfor %} -->


	

	{% endblock %}

blog/templates/blog/post_list.html
{% extends 'myblog/base.html' %}

	{% block content %}
			<div>
				{% for post in posts %}

					<div>

						<h2 class="h2-post-title shadow-lg p-3 mb-5 bg-white rounded"><a class="post-title " href="{%  url 'blog:detail' slug=post.slug %}" style="text-decoration: none;" >{{post.title}}</a></h2>

						<p class= "post-text shadow p-3 mb-5 bg-white rounded">{{post.snippet}}</p>

						<p class="published-date">Published by {{post.author}}  @{{post.published_date}}</p>



					</div>

				{% endfor %}

			</div>
	{% endblock %}
 

myblog/templates/myblog/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{%block title%}{%endblock%}</title>

		<!-- materializeCSS -->

<!-- 		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->

		<!-- bootsratp library include -->
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



		<!-- Source Static -->
		{% load staticfiles %}
		<!-- Source CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'base/css/styles.css' %}">
		<!-- Source JS -->
		<script type="text/javascript" src="{% static 'base/js/scripts.js' %}"></script>

	</head>
	
	<body >

		<!-- navbar -->

		<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">

			<div class="container">

				<!-- Website Icon -->

				  <a class="navbar-brand" href="{% url 'home' %}"><!-- <img src="/media/logo.png"> -->Simple Machi!</a>
				  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				    <span class="navbar-toggler-icon"></span>
				  </button>

			  <div class="collapse navbar-collapse" id="navbarSupportedContent">

			  	<!-- Common Page -->

				    <ul class="navbar-nav mr-auto">
				      <li class="nav-item">
				        <a class="nav-link" href="{%url 'home' %}">Home</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="{%url 'blog:posts' %}">Archive</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="#">Contact</a>
				      </li>

			    <!-- Premium Page -->

					 {% if request.user.is_authenticated %}

					    <li class="nav-item">
				        <a class="nav-link" href="{%url 'secret' %}">Secret</a>
				      	</li>	

					 {%endif%}

			    	</ul>

			    <!-- login and logout box -->

			    {% if request.user.is_authenticated %}

				    <ul class="navbar-nav">

				      <li class="nav-item dropdown">
				        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				          {{user.username}}
				        </a>
				        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
				          <a  class= "dropdown-item" href="{%url 'password_change' %}">Change password</a>
				          <div class="dropdown-divider"></div>
				          <a  class= "dropdown-item" href="{%url 'logout' %}">Logout</a>
				        </div>
				      </li>

				    </ul>

			    {%else%}

				    <form class="form-inline my-2 my-lg-0">

				    	<a  href="{%url 'login' %}" class="btn btn-outline-secondary">Login</a>
				    	<a  href="{%url 'signup' %}" class="btn btn-primary ml-2">Signup</a>
				    
				    </form>

			    {%endif%}

			  </div>

			</div> <!-- container -->

		</nav> <!-- navbar -->

		<!-- navbar -->

			
		<div class="container">

			<!-- mainpage content -->

				{% block content %}
				{% endblock %}

		</div><!-- container -->

	</body>
</html>

myblog/templates/myblog/home.html
{% extends 'myblog/test.html' %}

{%block title%}Home{%endblock%}

{% block content %}

	{% for post in posts %}

					<div>
	
						<!-- <p>Totle number of members: {{count}} and You are logged in as <strong>{{user}}</strong> </p> -->

						

						<span class="h2-post-title shadow-lg p-3 mb-5 bg-white rounded"><a class="post-title " href="{%  url 'blog:detail' slug=post.slug %}" style="text-decoration: none;" >{{post.title}}</a></span>

						<p class= "post-text shadow p-3 mb-5 bg-white rounded">{{post.snippet}}</p>

						<p class="published-date"> Published by {{post.author}}  @{{post.published_date}} </p>




					</div>

	{% endfor %}

							<ul class="nav nav-pills">
							  <span class="nav-item dropdown">
							    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
							    <div class="dropdown-menu">
							      <a class="dropdown-item" href="#">Action</a>
							      <a class="dropdown-item" href="#">Another action</a>
							      <a class="dropdown-item" href="#">Something else here</a>
							      <div class="dropdown-divider"></div>
							      <a class="dropdown-item" href="#">Separated link</a>
							    </div>
							  </li>
							</ul>
	
{% endblock %}

myblog/templates/myblog/secret_page.html
{%extends 'myblog/base.html' %}
{%block title%}Secret{%endblock%}

{% block content %}

	<h2>Welcome to the secret page</h2>


{% endblock %}

myblog/templates/myblog/signup.html
{% extends 'myblog/base.html'%}

{%block title%}Signup{%endblock%}

{% load crispy_forms_tags %}

{% block content %}

	<div class="row justify-content-center">
		<div class="row-6">
			<div class="card">
				<div class="card-body">

						<h2>Signup</h2>
						<form class="signup-form"  method="post">

							{%csrf_token%}

							{{form|crispy}}
							
							<button type="submit" class="btn btn-primary">Signup</button>

						</form>
					
				</div>
			</div>
		</div>
	</div>



{% endblock %}

<!-- action="/accounts/signup/" -->

myblog/templates/myblog/test.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{%block title%}{%endblock%}</title>

		<!-- materializeCSS -->

<!-- 		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->

		<!-- bootsratp library include -->
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



		<!-- Source Static -->
		{% load staticfiles %}
		<!-- Source CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'base/css/styles.css' %}">
		<!-- Source JS -->
		<script type="text/javascript" src="{% static 'base/js/scripts.js' %}"></script>

	</head>
	
	<body >

		<!-- navbar -->

		<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">

			<div class="container">

				<!-- Website Icon -->

				  <a class="navbar-brand" href="{% url 'home' %}"><!-- <img src="/media/logo.png"> -->Simple Machi!</a>
				  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				    <span class="navbar-toggler-icon"></span>
				  </button>

			  <div class="collapse navbar-collapse" id="navbarSupportedContent">

			  	<!-- Common Page -->

				    <ul class="navbar-nav mr-auto">
				      <li class="nav-item">
				        <a class="nav-link" href="{%url 'home' %}">Home</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="{%url 'blog:posts' %}">Archive</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="#">Contact</a>
				      </li>

			    <!-- Premium Page -->

					 {% if request.user.is_authenticated %}

					    <li class="nav-item">
				        <a class="nav-link" href="{%url 'secret' %}">Secret</a>
				      	</li>	

					 {%endif%}

			    	</ul>

			    <!-- login and logout box -->

			    {% if request.user.is_authenticated %}

				    <ul class="navbar-nav">

				      <li class="nav-item dropdown">
				        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				          {{user.username}}
				        </a>
				        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
				          <a  class= "dropdown-item" href="{%url 'password_change' %}">Change password</a>
				          <div class="dropdown-divider"></div>
				          <a  class= "dropdown-item" href="{%url 'logout' %}">Logout</a>
				        </div>
				      </li>

				    </ul>

			    {%else%}

				    <form class="form-inline my-2 my-lg-0">

				    	<a  href="{%url 'login' %}" class="btn btn-outline-secondary">Login</a>
				    	<a  href="{%url 'signup' %}" class="btn btn-primary ml-2">Signup</a>
				    
				    </form>

			    {%endif%}

			  </div>

			</div> <!-- container -->

		</nav> <!-- navbar -->

		<!-- navbar -->

			
		<div class="container">

			<!-- mainpage content -->

				{% block content %}
				{% endblock %}

		</div><!-- container -->

	</body>
</html>

myblog/templates/myblog/upload.html
{% extends "myblog/base.html" %}

{% block content%}
    <h2>upload</h2>
    <form method="post" enctype="multipart/form-data">
    	{% csrf_token %}
	    <input type="file" name="document" class="secondary-btn">
	    <button type="submit">Upload file</button>
    	
    </form>
    {%if url %}
	
		<p>Uploaded File: <a href="{{url}}">{{url}}</a></p> 


    {%endif%}
    
{% endblock %}

myblog/templates/navbar-backup.html
<!-- Navigation bar -->

			<!-- Navbar menu -->
		<nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-lg p-3 mb-5 bg-white rounded">


			<div class="collapse navbar-collapse" id ="collapse_target">
			
				<ul class="navbar-nav shadow-lg p-3 mb-5 bg-yellow rounded">
  					<li class="nav-item">
    					<a class="nav-link active" href="{%url 'home' %}">Home</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link active" href="{%url 'blog:posts' %}">Blog</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link active" href="#">Contact</a>
  					</li>
  					{% if request.user.is_authenticated %}

  						<li class="nav-item">
    						<a class="nav-link active" href="{%url 'password_change' %}">Change password</a>
  						</li>

  						<li class="nav-item">
    						<a class="nav-link active" href="{%url 'logout' %}">Logout</a>
  						</li>

  					{% else %}

  						<li class="nav-item">
    						<a class="nav-link active" href="{%url 'signup' %}">Signup</a>
  						</li>

  						<li class="nav-item">
    						<a class="nav-link active" href="{%url 'login' %}">Login</a>
  						</li>

  					{% endif %}
  					
  					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
          				<a class="dropdown-item" href="#">Action</a>
          				<a class="dropdown-item" href="#">Another action</a>
          			<div class="dropdown-divider"></div>
          				<a class="dropdown-item" href="#">Something else here</a>
        			</div>
  					

				</ul>

			</div>
			
			
			<span class="navbar-text brand-name">Simple Machi!</span>


			<!-- Toggle Button -->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapse_target" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">

				<span class="navbar-toggler-icon"></span>
			
			</button>

			
			</nav>